# Generated by Django 3.0.5 on 2023-03-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('stipend', models.PositiveIntegerField()),
                ('cutoff', models.PositiveIntegerField()),
                ('link', models.PositiveIntegerField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='exam_course',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('course_name', models.CharField(max_length=50)),
        #         ('total_marks', models.IntegerField()),
        #     ],
        # ),
    ]
