# Generated by Django 3.0.5 on 2023-03-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_companyform_exam_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('stipend', models.IntegerField()),
                ('cutoff', models.FloatField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='exam_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='questionbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='file/questionbank/')),
            ],
        ),
        migrations.DeleteModel(
            name='CompanyForm',
        ),
        migrations.AlterModelTable(
            name='result',
            table='exam_result',
        ),
    ]
