# Generated by Django 3.0.5 on 2023-03-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20230325_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='questionbank',
        ),
    ]
